### ISSUE TITLE
Inference resolution

### ISSUE THREAD

**Issue by jatentaki** [SMSD75/Timetuning#1]
Hi, cool work! I'd like to ask about inference resolution. You use vit variant for 224x224 images but your visualizations seem to indicate you run inference at higher resolutions. What are the settings you would suggest to someone interested in running the model without any additional finetuning?

**Comment by SMSD75** [comment]
Hi, thank you for your interest in our research. You can use cluster-based-foreground-extraction to get the visualizations. You can use either 224 or 448, but you have to revise the spatial resolution accordingly.
