### ISSUE TITLE
Time-Tuning with dinov2

### ISSUE THREAD

**Issue by memoiry** [SMSD75/Timetuning#2]
Hi,

I'm wondering have you tried the methods with dinov2 and compare to dinov2 to see how much improvement we could get? thanks.

**Comment by SMSD75** [comment]
Hi, 

Unfortunately not, but we will report the results on DinoV2 soon.

**Comment by AssafSinger94** [comment]
Hi Mohammadreza, really nice work! I was wondering if there are any updates on trained DinoV2 weights? 
Also, did you consider using LoRA for more efficient finetuning?

**Comment by SMSD75** [comment]
Hi,
Thank you for your interest in our work. We tried DINOv2, but it seems that we can not get consistent improvements on that backbone. About the second question, no we didn't do LoRA tuning. I have made another repo with a more modular implementation of TimeT here : https://github.com/SMSD75/TimeT_clean
Feel free to investigate other solutions there if you are interested.
