### ISSUE TITLE
KeyError when initialize a train_loader

### ISSUE THREAD

**Issue by akidway** [SMSD75/Timetuning#4]
Hi,
I'm a beginner of deep learning and I'm trying to reproduce this article.
When I try to initialize a train_loader, KeyError  occurred.
I guess there may be some an issue with data directory structure.
Could you help me?
Thanks a lot.

this is my code:
```
input_resolution = 224
video_transform_list = [video_transformations.Resize(input_resolution),
                                      video_transformations.RandomResizedCrop((input_resolution, input_resolution)), 
                                      video_transformations.RandomHorizontalFlip(), 
                                       video_transformations.ClipToTensor(mean=[0.485, 0.456, 0.406], std=[0.228, 0.224, 0.225])]
video_transform = video_transformations.Compose(video_transform_list)
train_loader = data_loader.make_loader("ytvos", num_clip_frames=1, batch_size=64, regular_step=1, 
                                       sampling_mode=data_loader.SamplingMode.UNIFORM,
                                       frame_transform=None, target_transform=None, video_transform=video_transform, shuffle=True,
                                       num_workers=0, pin_memory=True)

for i, train_data in enumerate(train_loader):
  data, annotations, label = train_data
  data = data.squeeze(1)
  print(data.shape)
```

and the error:
Traceback (most recent call last):
  File "D:\pythonProject\timeT\Timetuning-main\test.py", line 16, in <module>
    for i, train_data in enumerate(train_loader):
  File "D:\anaconda\envs\timeT\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "D:\anaconda\envs\timeT\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anaconda\envs\timeT\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anaconda\envs\timeT\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\pythonProject\timeT\Timetuning-main\data_loader.py", line 799, in __getitem__
    annotations = map_instances(annotations, self.meta_dict["videos"][dir_name]["objects"], self.category_dict)
KeyError: '00070'

data structure:
![structure](https://github.com/SMSD75/Timetuning/assets/93326359/e35ce489-1342-4040-b228-b81c5a4335c2)
![1](https://github.com/SMSD75/Timetuning/assets/93326359/5bc49312-82cb-4f51-8c37-9a9c58aa9a6d)

**Comment by akidway** [comment]
Finally when I change `num_labels=0` in function `make_loader`, this error disappear.
When `num_labels=0` , it will not create a folder for every image.

**Comment by SMSD75** [comment]
Hello and thank you for expressing interest in our research. To proceed, it's necessary to format your dataset according to the guidelines outlined on our main page. Should you prefer an automated approach to this conversion, it's important to note that the num_labels parameter determines the depth of recursive operations required to retrieve a video sample. For example, setting num_labels=2 implies an expected dataset structure organized as label_1/label_2.

**Comment by akidway** [comment]
Thank you very much.
